### PR TITLE
add error handling on invalid SQS message

### PR DESCRIPTION
**Pull request by geronimo-iia**
Hello,

The purpose of this change is to handle invalid message from SQS without stop current process.
When an invalid message is receive, the process must catch exception, log and remove invalid message from SQS queue.

It's my first pull request with node.js, so I'm sure we could do this in a better way...

I will do this in order to create a Docker image with a thumbd service ready to run (https://github.com/airdock-io/docker-thumbd). I have again little things to do on this image, but the tag 'ready for production' is not so far away.

Thanks a lot for you greath job !

Jerome

### CODE REVIEW

**Comment by bcoe** [comment]
@geronimo-iia thanks for the contribution, I will try to get this merged on the weekend -- just want to do some end to end testing first.

**Comment by bcoe** [comment]
@geronimo-iia I haven't had a chance to tackle this yet, but I haven't forgotten.

Is anyone else still using thumbd in production who can offer a review (@cohen-hyde, @seratonik, @aggied)?

**Comment by seratonik** [comment]
@bcoe I haven't had time to test it on my fork either - I've already had an issue with the queue getting hung up if there was an error and this would solve it. My only concern would be if there was a local issue on the machine doing the resizing, if the file gets removed from the queue it loses the chance that another worker could pick it up and complete successfully.

**Comment by geronimo-iia** [comment]
Hello,
@seratonik I'm totally agree with you about local issue/retry process.
What I would handle is invalid message that cannot be process because json message was invalid without stopping main process. But, this king of error occurs more often at dev time rather than in production (in most of case, we can hope)...

**Comment by seratonik** [comment]
I've brought these changes into my fork, and added some additional checks. I discovered that if no image descriptions were passed thumbd got stuck in an infinite loop of queue processing, and additionally it filled my entire hard drive with temp files. Can take a look here: https://github.com/Volinspire/thumbd  So far things appear to be working well.

**Comment by bcoe** [comment]
@seratonik awesome, will review as soon as possible.

**Comment by bcoe** [comment]
Closing in favor of https://github.com/bcoe/thumbd/pull/99

**Pull request closed without merging**
