### PR TITLE
Custom logger support

### PR DESCRIPTION
**Pull request by mathieumg**
As described in #102.

Tests are rudimentary, given some time I'd like a cleaner mock approach. Don't hesitate to point stuff out! The rationale is that we use a custom Sentry logger and would like to be aware of problems with our thumbd queue and only logging to the console won't help in that regard.

Thanks

### CODE REVIEW

**Comment by wiredmax** [comment]
Evertything is good, great job! Will merge it, but we'll have to wait for @bcoe to publish a new version on npm since it's under he's the author and owner of the package.

**Comment by mathieumg** [comment]
@bcoe Any way to get this published? Thanks!

**Comment by bcoe** [comment]
@mathieumg sorry about the slow reply! have been trying to dig myself out of an OSS backlog :)

I have published `thumbd@2.18.0` with the logger updates. I have also adde dyou and @wiredmax as owners on the GitHub repo and the npm module:

screen shot 2015-11-29 at 1 50 44 pm

Let me know anything else I can do to help :+1:

**Comment by wiredmax** [comment]
Awesome! thanks @bcoe ! :)

**Comment by mathieumg** [comment]
Perfect, thank you very much! :smile:

**Pull request merged**
