### PR TITLE
merge jshint fixes, fixed a couple issues introduced by the patch

### PR DESCRIPTION
**Pull request by bcoe**
* thumbnailer has state, so a new instance is required per thumbnail, I've updated constructors to better reflect this requirement.
* I figured I might as well upgrade thumbd to use yargs, since I'm doing manual testing any ways.

### CODE REVIEW

**Comment by rubenstolk** [comment]
Oh sorry, I see that you removed that option of sending the thumbnailer to the Worker.

**Comment by rubenstolk** [comment]
As mentioned in https://github.com/bcoe/thumbd/issues/90, you're using quite some closures here and there which is why I suspect the memory leaks. `new Thumbnailer` everytime could be one of those closures as well?

**Comment by bcoe** [comment]
@rubenstolk it would take a bit of refactoring to make `Thumbnailer()` contain no state., which is why a new instance is required each time. Otherwise exceptions various exceptions occur related to callbacks being executed multiple times with `async`.

**Comment by bcoe** [comment]
I doubt the memory leak is related to the new instance of thumbnailer, as the problem does not manifest itself in `0.10.36` of Node.js. 

We had a very similar problem on Heroku a few months back:

https://github.com/bcoe/thumbd/issues/63

Any ways, my preference would be to get the fixes merged for jshint; and to tackle the memory leak in a different pull-request.

**Comment by rubenstolk** [comment]
Thanks @bcoe!

**Pull request merged**
