### PR TITLE
Support signature version 4

### PR DESCRIPTION
**Pull request by fansaien**
1.Support signature version 4 
2.Removed knox and use AWS SDK directly

Didn't support HTTP right now, maybe need call "putBucketWebsite".
But I can't do it in China, as we can't access S3 through http before the domain name has been acquired the ICP license. 

So, it can't pass the test-client.js

### CODE REVIEW

**Comment by bcoe** [comment]
releasing a huge project at work this week, but will work on getting this merged as soon as I have some time to hack on the weekend.

**Comment by bcoe** [comment]
@fansaien I haven't forgotten about this pull request. I've unfortunately been swamped by other projects/work. How has this branch been working out for you in production?

**Comment by fansaien** [comment]
@bcoe I haven't released my product, but it works on my test server very well. It can't pass the CI build because it does't support connection via http proxy.

**Comment by bcoe** [comment]
@fansaien I like the idea of swapping out the S3 library, but... I haven't had the time to get tests around the new functionality, and there are several people who have applications in production using thumbd, so I'm hesitant to merge this until someone has tested in a production environment.

I'm going to closet this for the time being, since it now conflicts with what is on master. Let's revisit this in the future though, when we have some time to put against getting thorough unit tests in place.

**Pull request closed without merging**
