### PR TITLE
Bump aws-sdk

### PR DESCRIPTION
**Pull request by rubenstolk**
Fixes memory leak issues (visible on Heroku)

### CODE REVIEW

**Comment by rubenstolk** [comment]
@bcoe can you please merge this PR and publish to `npm`?

**Comment by rubenstolk** [comment]
Fixes #90

**Comment by bcoe** [comment]
:+1: will get this merged today, thanks for the patch!

**Comment by bcoe** [comment]
@rubenstolk I've released `thumbd@2.16.2`, let me know if it solves your problems.

**Comment by rubenstolk** [comment]
Thanks so much, it's definitely solved an issue!

--

Ruben Stolk

http://changer.nl, "Raising the bar in online experience"
+91 95 6105 0034   /  +31 6 46 11 80 37

**Pull request merged**
